apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
    - port: 3306
      targetPort: 3306
      name: mysql
  selector:
    app: mysql
  clusterIP: None

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mysql
  name: mysql
spec:
  replicas: 1 # ensure only one pod running
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:8.0
          name: mysql
          resources: # assign resource for mysql to prevent overload
            requests:
              cpu: "200m"
              memory: "2.0G"
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: root_password
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage # vol1 : persistentVolumeClaim
              mountPath: /var/lib/mysql
            - name: mysql-config-volume # vol2 : configMap
              mountPath: /etc/mysql/conf.d/my.cnf
              subPath: my.cnf
      volumes:
        - name: mysql-persistent-storage # vol1
          persistentVolumeClaim:
            claimName: mysql-pv-claim
        - name: mysql-config-volume # vol2
          configMap:
            name: mysql-config-map
